#!/bin/bash -ex

ENV=install-test-env
#[ ! -d $ENV ]
virtualenv $ENV
. $ENV/bin/activate

PACKAGE=seqan
PYPI=pyseqan
REPO=pyseqan
UNINSTALL="pip uninstall --yes $PYPI"

# Install from git
pip install git+https://github.com/JohnReid/$REPO.git
python -c "import $PACKAGE"
$UNINSTALL

# Install from PyPI
pip install $PYPI
python -c "import $PACKAGE"
$UNINSTALL

# Install local version
python setup.py install
python -c "import $PACKAGE"

