#!/bin/bash -ex

#
# Create and activate the virtual environment
#
virtualenv virtualenv
. virtualenv/bin/activate
UPDATE="pip install -U"


#
# Install some packages we will need
#
$UPDATE cookbook
$UPDATE nose
$UPDATE sphinx
$UPDATE sphinx-pypi-upload

#
# Add python directory to path
#
echo "/home/john/Dev/pyseqan/python" > virtualenv/lib/python2.7/site-packages/seqan.pth


