#!/bin/bash -e

. ./setup

ARGS="--leak-check=full --error-limit=no --suppressions=sequan-2.supp --gen-suppressions=all"
VALGRIND="valgrind $ARGS"
export PYSEQANDEBUG=1

# Create suppressions file for general python seqan suppressions
$VALGRIND --log-file=tmp.log "$@" >tmp.out
cat tmp.log | parse-valgrind-suppressions

